### ISSUE TITLE
Evaluation problem activity 

### ISSUE THREAD

**Issue by yob601** [ereflog/Stargazing#14]
1. Obslogbook error (done) by 
     @fortunofaqih

2. Imaging-guiding ratio calc (done) 
     by @anteknik 

3. Integration HMS kit (done) by @ereflog

**Comment by ereflog** [comment]
HMS kit integration done

**Comment by fortunofaqih** [comment]
integration layout input date (done)
integration layout input time (on progress)
add layout add, edit, delete (on progress)

**Comment by anteknik** [comment]
Imaging-guiding ratio calc (update / done )
by @anteknik

**Comment by yob601** [comment]
Evaluation #1 solved
