### ISSUE TITLE
Evaluation Add and Challenge Team

### ISSUE THREAD

**Issue by yob601** [ereflog/Stargazing#17]
1. Add layout data input Obslogbook add, edit and 
   delete (done) {by @fortunofaqih}

     Challenge Team :
2. add location kit (done) {by @yob601}
3. Add push kit (done) {by @ereflog}
4. Add ads kit (done) {by @yob601}
5. Add analitic kit (done) {by @anteknik}
6. Add databases {obslogbook} cloud.db (check on console) {by @ereflog}

**Comment by fortunofaqih** [comment]
already pull fix time and date input, next add, edit, delete

**Comment by anteknik** [comment]
Add analitic kit (in progress) {by @anteknik  on progress}

**Comment by anteknik** [comment]
Add analitic kit by @anteknik  updated}

1. user attributes getAAID 
2. popular reportPage (custom event)

kindly check result on  HUAWEI Analytics > Overview > Real-time overview. 
to @ereflog  & @yob601  thanks

**Comment by anteknik** [comment]
Add analitic kit by @anteknik updated}

1. user attributes getAAID
2. popular reportPage (custom event)
3.  ObsLogBook class custom event analytic
a.data object field
b.data observer field
c. data latitude,longtitude field
d ......

**Comment by fortunofaqih** [comment]
add layout floating button and dummy data
